### ISSUE TITLE
 error: package generateSDG does not exist

### ISSUE THREAD

**Issue by bupt01** [PLaSSticity/SDP-WDP-implementation#1]
I encountered a 'BUILD FAILED' error when I ran the 'ant' command in the software's folder during the installation.Here are the specific details：
![image](https://github.com/PLaSSticity/SDP-WDP-implementation/assets/73539951/c8019dac-566d-464b-a497-54ce367a9132)

I wonder if, when you uploaded the source code, you accidentally missed some files

**Comment by mdbond** [comment]
Hmm, it does look like we may have missed some files. See attachment. Does adding those files fix the issue?
[extra.tar.gz](https://github.com/PLaSSticity/SDP-WDP-implementation/files/13301351/extra.tar.gz)

**Comment by bupt01** [comment]
Thank you, the issue was resolved after adding the file.
