### ISSUE TITLE
Request for IntelliJ IDEA Version Used in the Project

### ISSUE THREAD

**Issue by bupt01** [PLaSSticity/SDP-WDP-implementation#2]
Hello,
I am currently studying your code, aiming to gain a deeper understanding of its underlying principles. To facilitate my learning and streamline the debugging process, would it be possible for you to provide the IntelliJ IDEA project files for the source code?
Thank you for your open-source contributions!
Best regards！

**Comment by mdbond** [comment]
Sorry, we didn't use IntelliJ IDEA and don't have any project files for it. I think we used Visual Studio Code for development, but still built the code with the Ant script.

**Comment by bupt01** [comment]
Got it, thank you.

**Comment by bupt01** [comment]
Thanks to the author for the enthusiastic answers
