### ISSUE TITLE
How to analyze using SDP and WDP?

### ISSUE THREAD

**Issue by bupt01** [PLaSSticity/SDP-WDP-implementation#3]
I'm sorry to bother you. After downloading the source code, I use `ant` ，`source msetup`
and then use the command `rrrun -tools`
It seems that I couldn't find the SDP and WDP tools：

![image](https://github.com/PLaSSticity/SDP-WDP-implementation/assets/73539951/5eb64aac-fc6b-4899-832b-5c21d158c472)

Then I used the command: `rrrun -brVindicateNWCRaces -dcWCP_NWC_WBR -quiet -noxml test > test.rr`.However, for some reason, it did not detect any data races.The results of the execution are as follows:

![image](https://github.com/PLaSSticity/SDP-WDP-implementation/assets/73539951/f9a22347-1c24-4255-92e6-a9851fa58d91)
The code contents of test.java are as follows:
`
public class test {
    /**
     * This is Figure 2.a in the paper.
     * No predictable race exists.
     *
     * WDP (WBR) will report a false race here.
     */

    static int dataRace = 0;

    public static class Thread1 extends Thread implements Runnable {
        @Override
        public void run() {
            dataRace=1;
        }
    }

    public static class Thread2 extends Thread implements Runnable {
        @Override
        public void run() {
            dataRace=2;
        }
    }

    public static void main(String args[]) throws Exception {
        Thread t1 = new Thread1();
        Thread t2 = new Thread2();

        t1.start();
        t2.start();

        t1.join();
        t2.join();
    }
}
`

**Comment by bupt01** [comment]
In addition, I noticed that "WBR" did not appear in the paper. I would like to know the relationship between WBR and SDP as well as WDP.

**Comment by mdbond** [comment]
WDP is called WBR in the implementation. SDP is called NWC in the implementation. (I also see XDP in the implementation, which seems related to SDP/NWC, but I don't remember more. XDP may be related to the fact that we had to change SDP in order to make a sound relation.)

**Comment by bupt01** [comment]
Sure, thank you. I have another question. Existing algorithms for detecting data races are either implemented based on Rapid or based on RoadRunner. Compared to Rapid, RoadRunner also has the capability to generate traces, whereas Rapid requires other tools to provide input traces. I noticed that your implementation is based on RoadRunner, which processes corresponding events directly when running the tested program without storing the events.
Recently, I've been using Rapid to detect data races and employing RoadRunner to record and generate traces(rrrun -noFP -tool=P -values -noxml -noEnter -quiet ). However, I quickly noticed that RoadRunner's recording of traces doesn't seem to stop at all.In many benchmarks, this seems to be a common issue, such as in benchmarks like Moldyn and Raytracer.In contrast, running the tested program directly concludes within a few seconds. While recording traces may naturally slow down the execution speed, the pace of RoadRunner seems excessively abnormal. Additionally, the generated number of traces is exceptionally high, reaching hundreds of millions of events. This is significantly different from the event counts reported in the literature for other data race detection tools.
I would like to know if you have encountered such an issue and how you resolved it. Does this indicate that it might be more prudent to directly implement the corresponding data race detection algorithm using RoadRunner, rather than attempting to use RoadRunner to record trace information for offline analysis?

**Comment by bupt01** [comment]
Thank you
